spring.application.name=pedidos-service
server.port=8082

# Conexión a la Base de Datos (variables de entorno con default local)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/pasteleria_my_dreams?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Kafka local (broker en docker, topic creado por docker-compose.yml)
spring.kafka.bootstrap-servers=localhost:9092
app.kafka.topic=pedidos
